# Generated by Django 3.0.7 on 2020-07-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_auto_20200702_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadform',
            old_name='submitted',
            new_name='created',
        ),
    ]
