# Generated by Django 3.0.7 on 2020-07-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_auto_20200704_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
