# Generated by Django 3.0.7 on 2020-07-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0007_uploadform_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('spent_money', models.IntegerField()),
                ('gems', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bidding',
            name='new',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
